# Generated by Django 5.2.8 on 2025-11-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChicShot_Payment_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='user_id',
            new_name='fb_id',
        ),
    ]
